name: Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ·ï¸ Collect tag name
        id: tag
        run: |
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name : ğŸ‹ Build docker image
        run: make docker-build
      - name: ğŸ”‘ Login docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ğŸ“¦ Push docker image
        run: make docker-push